export const pokemonNames = [
  'bulbasaur',
  'ivysaur',
  'venusaur',
  'venusaurmega venusaur',
  'charmander',
  'charmeleon',
  'charizard',
  'charizardmega charizard x',
  'charizardmega charizard y',
  'squirtle',
  'wartortle',
  'blastoise',
  'blastoisemega blastoise',
  'caterpie',
  'metapod',
  'butterfree',
  'weedle',
  'kakuna',
  'beedrill',
  'beedrillmega beedrill',
  'pidgey',
  'pidgeotto',
  'pidgeot',
  'pidgeotmega pidgeot',
  'rattata',
  'raticate',
  'spearow',
  'fearow',
  'ekans',
  'arbok',
  'pikachu',
  'raichu',
  'sandshrew',
  'sandslash',
  'nidoran♀',
  'nidorina',
  'nidoqueen',
  'nidoran♂',
  'nidorino',
  'nidoking',
  'clefairy',
  'clefable',
  'vulpix',
  'ninetales',
  'jigglypuff',
  'wigglytuff',
  'zubat',
  'golbat',
  'oddish',
  'gloom',
  'vileplume',
  'paras',
  'parasect',
  'venonat',
  'venomoth',
  'diglett',
  'dugtrio',
  'meowth',
  'persian',
  'psyduck',
  'golduck',
  'mankey',
  'primeape',
  'growlithe',
  'arcanine',
  'poliwag',
  'poliwhirl',
  'poliwrath',
  'abra',
  'kadabra',
  'alakazam',
  'alakazammega alakazam',
  'machop',
  'machoke',
  'machamp',
  'bellsprout',
  'weepinbell',
  'victreebel',
  'tentacool',
  'tentacruel',
  'geodude',
  'graveler',
  'golem',
  'ponyta',
  'rapidash',
  'slowpoke',
  'slowbro',
  'slowbromega slowbro',
  'magnemite',
  'magneton',
  "farfetch'd",
  'doduo',
  'dodrio',
  'seel',
  'dewgong',
  'grimer',
  'muk',
  'shellder',
  'cloyster',
  'gastly',
  'haunter',
  'gengar',
  'gengarmega gengar',
  'onix',
  'drowzee',
  'hypno',
  'krabby',
  'kingler',
  'voltorb',
  'electrode',
  'exeggcute',
  'exeggutor',
  'cubone',
  'marowak',
  'hitmonlee',
  'hitmonchan',
  'lickitung',
  'koffing',
  'weezing',
  'rhyhorn',
  'rhydon',
  'chansey',
  'tangela',
  'kangaskhan',
  'kangaskhanmega kangaskhan',
  'horsea',
  'seadra',
  'goldeen',
  'seaking',
  'staryu',
  'starmie',
  'mr. mime',
  'scyther',
  'jynx',
  'electabuzz',
  'magmar',
  'pinsir',
  'pinsirmega pinsir',
  'tauros',
  'magikarp',
  'gyarados',
  'gyaradosmega gyarados',
  'lapras',
  'ditto',
  'eevee',
  'vaporeon',
  'jolteon',
  'flareon',
  'porygon',
  'omanyte',
  'omastar',
  'kabuto',
  'kabutops',
  'aerodactyl',
  'aerodactylmega aerodactyl',
  'snorlax',
  'articuno',
  'zapdos',
  'moltres',
  'dratini',
  'dragonair',
  'dragonite',
  'mewtwo',
  'mewtwomega mewtwo x',
  'mewtwomega mewtwo y',
  'mew',
  'chikorita',
  'bayleef',
  'meganium',
  'cyndaquil',
  'quilava',
  'typhlosion',
  'totodile',
  'croconaw',
  'feraligatr',
  'sentret',
  'furret',
  'hoothoot',
  'noctowl',
  'ledyba',
  'ledian',
  'spinarak',
  'ariados',
  'crobat',
  'chinchou',
  'lanturn',
  'pichu',
  'cleffa',
  'igglybuff',
  'togepi',
  'togetic',
  'natu',
  'xatu',
  'mareep',
  'flaaffy',
  'ampharos',
  'ampharosmega ampharos',
  'bellossom',
  'marill',
  'azumarill',
  'sudowoodo',
  'politoed',
  'hoppip',
  'skiploom',
  'jumpluff',
  'aipom',
  'sunkern',
  'sunflora',
  'yanma',
  'wooper',
  'quagsire',
  'espeon',
  'umbreon',
  'murkrow',
  'slowking',
  'misdreavus',
  'unown',
  'wobbuffet',
  'girafarig',
  'pineco',
  'forretress',
  'dunsparce',
  'gligar',
  'steelix',
  'steelixmega steelix',
  'snubbull',
  'granbull',
  'qwilfish',
  'scizor',
  'scizormega scizor',
  'shuckle',
  'heracross',
  'heracrossmega heracross',
  'sneasel',
  'teddiursa',
  'ursaring',
  'slugma',
  'magcargo',
  'swinub',
  'piloswine',
  'corsola',
  'remoraid',
  'octillery',
  'delibird',
  'mantine',
  'skarmory',
  'houndour',
  'houndoom',
  'houndoommega houndoom',
  'kingdra',
  'phanpy',
  'donphan',
  'porygon2',
  'stantler',
  'smeargle',
  'tyrogue',
  'hitmontop',
  'smoochum',
  'elekid',
  'magby',
  'miltank',
  'blissey',
  'raikou',
  'entei',
  'suicune',
  'larvitar',
  'pupitar',
  'tyranitar',
  'tyranitarmega tyranitar',
  'lugia',
  'ho-oh',
  'celebi',
  'treecko',
  'grovyle',
  'sceptile',
  'sceptilemega sceptile',
  'torchic',
  'combusken',
  'blaziken',
  'blazikenmega blaziken',
  'mudkip',
  'marshtomp',
  'swampert',
  'swampertmega swampert',
  'poochyena',
  'mightyena',
  'zigzagoon',
  'linoone',
  'wurmple',
  'silcoon',
  'beautifly',
  'cascoon',
  'dustox',
  'lotad',
  'lombre',
  'ludicolo',
  'seedot',
  'nuzleaf',
  'shiftry',
  'taillow',
  'swellow',
  'wingull',
  'pelipper',
  'ralts',
  'kirlia',
  'gardevoir',
  'gardevoirmega gardevoir',
  'surskit',
  'masquerain',
  'shroomish',
  'breloom',
  'slakoth',
  'vigoroth',
  'slaking',
  'nincada',
  'ninjask',
  'shedinja',
  'whismur',
  'loudred',
  'exploud',
  'makuhita',
  'hariyama',
  'azurill',
  'nosepass',
  'skitty',
  'delcatty',
  'sableye',
  'sableyemega sableye',
  'mawile',
  'mawilemega mawile',
  'aron',
  'lairon',
  'aggron',
  'aggronmega aggron',
  'meditite',
  'medicham',
  'medichammega medicham',
  'electrike',
  'manectric',
  'manectricmega manectric',
  'plusle',
  'minun',
  'volbeat',
  'illumise',
  'roselia',
  'gulpin',
  'swalot',
  'carvanha',
  'sharpedo',
  'sharpedomega sharpedo',
  'wailmer',
  'wailord',
  'numel',
  'camerupt',
  'cameruptmega camerupt',
  'torkoal',
  'spoink',
  'grumpig',
  'spinda',
  'trapinch',
  'vibrava',
  'flygon',
  'cacnea',
  'cacturne',
  'swablu',
  'altaria',
  'altariamega altaria',
  'zangoose',
  'seviper',
  'lunatone',
  'solrock',
  'barboach',
  'whiscash',
  'corphish',
  'crawdaunt',
  'baltoy',
  'claydol',
  'lileep',
  'cradily',
  'anorith',
  'armaldo',
  'feebas',
  'milotic',
  'castform',
  'kecleon',
  'shuppet',
  'banette',
  'banettemega banette',
  'duskull',
  'dusclops',
  'tropius',
  'chimecho',
  'absol',
  'absolmega absol',
  'wynaut',
  'snorunt',
  'glalie',
  'glaliemega glalie',
  'spheal',
  'sealeo',
  'walrein',
  'clamperl',
  'huntail',
  'gorebyss',
  'relicanth',
  'luvdisc',
  'bagon',
  'shelgon',
  'salamence',
  'salamencemega salamence',
  'beldum',
  'metang',
  'metagross',
  'metagrossmega metagross',
  'regirock',
  'regice',
  'registeel',
  'latias',
  'latiasmega latias',
  'latios',
  'latiosmega latios',
  'kyogre',
  'kyogreprimal kyogre',
  'groudon',
  'groudonprimal groudon',
  'rayquaza',
  'rayquazamega rayquaza',
  'jirachi',
  'deoxysnormal forme',
  'deoxysattack forme',
  'deoxysdefense forme',
  'deoxysspeed forme',
  'turtwig',
  'grotle',
  'torterra',
  'chimchar',
  'monferno',
  'infernape',
  'piplup',
  'prinplup',
  'empoleon',
  'starly',
  'staravia',
  'staraptor',
  'bidoof',
  'bibarel',
  'kricketot',
  'kricketune',
  'shinx',
  'luxio',
  'luxray',
  'budew',
  'roserade',
  'cranidos',
  'rampardos',
  'shieldon',
  'bastiodon',
  'burmy',
  'wormadamplant cloak',
  'wormadamsandy cloak',
  'wormadamtrash cloak',
  'mothim',
  'combee',
  'vespiquen',
  'pachirisu',
  'buizel',
  'floatzel',
  'cherubi',
  'cherrim',
  'shellos',
  'gastrodon',
  'ambipom',
  'drifloon',
  'drifblim',
  'buneary',
  'lopunny',
  'lopunnymega lopunny',
  'mismagius',
  'honchkrow',
  'glameow',
  'purugly',
  'chingling',
  'stunky',
  'skuntank',
  'bronzor',
  'bronzong',
  'bonsly',
  'mime jr.',
  'happiny',
  'chatot',
  'spiritomb',
  'gible',
  'gabite',
  'garchomp',
  'garchompmega garchomp',
  'munchlax',
  'riolu',
  'lucario',
  'lucariomega lucario',
  'hippopotas',
  'hippowdon',
  'skorupi',
  'drapion',
  'croagunk',
  'toxicroak',
  'carnivine',
  'finneon',
  'lumineon',
  'mantyke',
  'snover',
  'abomasnow',
  'abomasnowmega abomasnow',
  'weavile',
  'magnezone',
  'lickilicky',
  'rhyperior',
  'tangrowth',
  'electivire',
  'magmortar',
  'togekiss',
  'yanmega',
  'leafeon',
  'glaceon',
  'gliscor',
  'mamoswine',
  'porygon-z',
  'gallade',
  'gallademega gallade',
  'probopass',
  'dusknoir',
  'froslass',
  'rotom',
  'rotomheat rotom',
  'rotomwash rotom',
  'rotomfrost rotom',
  'rotomfan rotom',
  'rotommow rotom',
  'uxie',
  'mesprit',
  'azelf',
  'dialga',
  'palkia',
  'heatran',
  'regigigas',
  'giratinaaltered forme',
  'giratinaorigin forme',
  'cresselia',
  'phione',
  'manaphy',
  'darkrai',
  'shayminland forme',
  'shayminsky forme',
  'arceus',
  'victini',
  'snivy',
  'servine',
  'serperior',
  'tepig',
  'pignite',
  'emboar',
  'oshawott',
  'dewott',
  'samurott',
  'patrat',
  'watchog',
  'lillipup',
  'herdier',
  'stoutland',
  'purrloin',
  'liepard',
  'pansage',
  'simisage',
  'pansear',
  'simisear',
  'panpour',
  'simipour',
  'munna',
  'musharna',
  'pidove',
  'tranquill',
  'unfezant',
  'blitzle',
  'zebstrika',
  'roggenrola',
  'boldore',
  'gigalith',
  'woobat',
  'swoobat',
  'drilbur',
  'excadrill',
  'audino',
  'audinomega audino',
  'timburr',
  'gurdurr',
  'conkeldurr',
  'tympole',
  'palpitoad',
  'seismitoad',
  'throh',
  'sawk',
  'sewaddle',
  'swadloon',
  'leavanny',
  'venipede',
  'whirlipede',
  'scolipede',
  'cottonee',
  'whimsicott',
  'petilil',
  'lilligant',
  'basculin',
  'sandile',
  'krokorok',
  'krookodile',
  'darumaka',
  'darmanitanstandard mode',
  'darmanitanzen mode',
  'maractus',
  'dwebble',
  'crustle',
  'scraggy',
  'scrafty',
  'sigilyph',
  'yamask',
  'cofagrigus',
  'tirtouga',
  'carracosta',
  'archen',
  'archeops',
  'trubbish',
  'garbodor',
  'zorua',
  'zoroark',
  'minccino',
  'cinccino',
  'gothita',
  'gothorita',
  'gothitelle',
  'solosis',
  'duosion',
  'reuniclus',
  'ducklett',
  'swanna',
  'vanillite',
  'vanillish',
  'vanilluxe',
  'deerling',
  'sawsbuck',
  'emolga',
  'karrablast',
  'escavalier',
  'foongus',
  'amoonguss',
  'frillish',
  'jellicent',
  'alomomola',
  'joltik',
  'galvantula',
  'ferroseed',
  'ferrothorn',
  'klink',
  'klang',
  'klinklang',
  'tynamo',
  'eelektrik',
  'eelektross',
  'elgyem',
  'beheeyem',
  'litwick',
  'lampent',
  'chandelure',
  'axew',
  'fraxure',
  'haxorus',
  'cubchoo',
  'beartic',
  'cryogonal',
  'shelmet',
  'accelgor',
  'stunfisk',
  'mienfoo',
  'mienshao',
  'druddigon',
  'golett',
  'golurk',
  'pawniard',
  'bisharp',
  'bouffalant',
  'rufflet',
  'braviary',
  'vullaby',
  'mandibuzz',
  'heatmor',
  'durant',
  'deino',
  'zweilous',
  'hydreigon',
  'larvesta',
  'volcarona',
  'cobalion',
  'terrakion',
  'virizion',
  'tornadusincarnate forme',
  'tornadustherian forme',
  'thundurusincarnate forme',
  'thundurustherian forme',
  'reshiram',
  'zekrom',
  'landorusincarnate forme',
  'landorustherian forme',
  'kyurem',
  'kyuremblack kyurem',
  'kyuremwhite kyurem',
  'keldeoordinary forme',
  'keldeoresolute forme',
  'meloettaaria forme',
  'meloettapirouette forme',
  'genesect',
  'chespin',
  'quilladin',
  'chesnaught',
  'fennekin',
  'braixen',
  'delphox',
  'froakie',
  'frogadier',
  'greninja',
  'bunnelby',
  'diggersby',
  'fletchling',
  'fletchinder',
  'talonflame',
  'scatterbug',
  'spewpa',
  'vivillon',
  'litleo',
  'pyroar',
  'flabébé',
  'floette',
  'florges',
  'skiddo',
  'gogoat',
  'pancham',
  'pangoro',
  'furfrou',
  'espurr',
  'meowsticmale',
  'meowsticfemale',
  'honedge',
  'doublade',
  'aegislashblade forme',
  'aegislashshield forme',
  'spritzee',
  'aromatisse',
  'swirlix',
  'slurpuff',
  'inkay',
  'malamar',
  'binacle',
  'barbaracle',
  'skrelp',
  'dragalge',
  'clauncher',
  'clawitzer',
  'helioptile',
  'heliolisk',
  'tyrunt',
  'tyrantrum',
  'amaura',
  'aurorus',
  'sylveon',
  'hawlucha',
  'dedenne',
  'carbink',
  'goomy',
  'sliggoo',
  'goodra',
  'klefki',
  'phantump',
  'trevenant',
  'pumpkabooaverage size',
  'pumpkaboosmall size',
  'pumpkaboolarge size',
  'pumpkaboosuper size',
  'gourgeistaverage size',
  'gourgeistsmall size',
  'gourgeistlarge size',
  'gourgeistsuper size',
  'bergmite',
  'avalugg',
  'noibat',
  'noivern',
  'xerneas',
  'yveltal',
  'zygarde50% forme',
  'diancie',
  'dianciemega diancie',
  'hoopahoopa confined',
  'hoopahoopa unbound',
  'volcanion',
];
