"""Add sprites to players

Revision ID: abc0b9da9b18
Revises: 3dbd8ce6670c
Create Date: 2023-06-01 23:26:52.539446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from app.common.pokemon import random_pokemon
from app.models.db import Player


# revision identifiers, used by Alembic.
revision = 'abc0b9da9b18'
down_revision = '3dbd8ce6670c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('sprite', sa.String(length=20), nullable=False, default=lambda: random_pokemon()))
    op.add_column('session_data', sa.Column('straight_flush', sa.Numeric(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'sprite')
    op.drop_table('session_data', 'straight_flush')
    # ### end Alembic commands ###
